# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: openbus-collaboration-service
    - GH_REPO_REF: github.com/amadeubarbosa/openbus-collaboration-service.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - cd docs
  - doxygen collab.dox

# Generate and deploy documentation
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd docs/html
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='Amadeu Andrade Barbosa Junior' -c user.email='amadeu@tecgraf.puc-rio.br' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://amadeubarbosa:$GITHUB_API_KEY@github.com/amadeubarbosa/openbus-collaboration-service.git gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
