# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_REF: github.com/amadeubarbosa/openbus-collaboration-service.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - cd docs
  - doxygen collab.dox

# Generate and deploy documentation
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd docs
    git add --all
    git -c user.name='Amadeu Andrade Barbosa Junior' -c user.email='amadeu@tecgraf.puc-rio.br' commit -m "Deploying by Travis CI - $TRAVIS_BUILD_NUMBER"
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://amadeubarbosa:$GITHUB_API_KEY@$GH_REPO_REF
    cd "$TRAVIS_BUILD_DIR"
  fi
