#ifndef __TECGRAF_OPENBUS_COLLABORATION_DEMO_HELLO_IDL__
#define __TECGRAF_OPENBUS_COLLABORATION_DEMO_HELLO_IDL__

#include "collaboration.idl"

/**
 * \brief Módulo dos sistemas e aplicações do Tecgraf.
 */
module tecgraf {

/**
 * \brief Módulo do middleware OpenBus.
 */
module openbus {

/**
 * \brief Módulo de definições de serviços do OpenBus.
 */
module services {

/**
 * \brief Módulo de definições do serviço de colaboração do OpenBus.
 */
module collaboration {

/**
 * \brief Módulo de versionamento do serviço de colaboração.
 */
module v1_0 {

    /** \brief Nome da faceta do membro da colaboração. */
    const string CollaborationSessionMemberFacet = "SessionMember";

    interface CollaborationSessionMember {
      void sayHello(in CollaborationMember newMember);
      void reply(in Identifier name);
    };
}; // version

}; // collaboration

}; // services

}; // openbus

}; // tecgraf


#endif
